version: '3'
services:
    camunda:
        image: camunda/camunda-bpm-platform:${DISTRO:-latest}
        environment:
            - DB_DRIVER=org.postgresql.Driver
            - DB_URL=jdbc:postgresql://postgres:5432/camunda
            - DB_USERNAME=camunda
            - DB_PASSWORD=camunda
            - WAIT_FOR=postgres:5432
        hostname: camunda
        links:
            - postgres
        ports:
            - "8080:8080"
        volumes:
          - "$PWD/camunda_client/target/CamundaClient-1.0.war:/camunda/webapps/CamundaClient-1.0.war"
        restart: unless-stopped

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=camunda
            - POSTGRES_PASSWORD=camunda
        hostname: postgres

    data-collector:
        image: lyr3x/data-collector
        ports:
          - "9050:9050"
        hostname: data-collector